import type { Product, Category } from './types'

export const categories: Category[] = [
  { id: 'mode', name: 'Mode', icon: 'Shirt', count: 2450 },
  { id: 'electronique', name: 'Electronique', icon: 'Smartphone', count: 1820 },
  { id: 'maison', name: 'Maison & Deco', icon: 'Lamp', count: 980 },
  { id: 'beaute', name: 'Beaute', icon: 'Sparkles', count: 1340 },
  { id: 'sport', name: 'Sport', icon: 'Dumbbell', count: 760 },
  { id: 'accessoires', name: 'Accessoires', icon: 'Watch', count: 2100 },
  { id: 'enfants', name: 'Enfants', icon: 'Baby', count: 540 },
  { id: 'high-tech', name: 'High-Tech', icon: 'Laptop', count: 890 },
]

export const trendingProducts: Product[] = [
  {
    id: 'p1',
    name: 'Ensemble Accessoires Premium',
    price: 45000,
    originalPrice: 62000,
    image: '/images/products/trending-1.jpg',
    source: 'Amazon',
    category: 'accessoires',
    badge: 'Soldes',
    deliveryDays: '7-12 jours',
    rating: 4.8,
    reviews: 234,
    description: 'Un ensemble complet d\'accessoires premium comprenant lunettes de soleil, montre et sac a main. Qualite superieure et design moderne.',
    sizes: ['Unique'],
    colors: [
      { name: 'Noir', hex: '#1C0A00' },
      { name: 'Marron', hex: '#6B4C2A' },
    ],
  },
  {
    id: 'p2',
    name: 'Ecouteurs Bluetooth Sans Fil',
    price: 18500,
    originalPrice: 25000,
    image: '/images/products/trending-2.jpg',
    source: 'AliExpress',
    category: 'electronique',
    badge: 'Populaire',
    deliveryDays: '10-15 jours',
    rating: 4.6,
    reviews: 1089,
    description: 'Ecouteurs bluetooth sans fil avec boitier de charge. Son haute qualite, reduction de bruit active et autonomie de 24h.',
    colors: [
      { name: 'Blanc', hex: '#FFFFFF' },
      { name: 'Noir', hex: '#1C0A00' },
    ],
  },
  {
    id: 'p3',
    name: 'Sac Bandouliere Cuir Minimaliste',
    price: 32000,
    image: '/images/products/trending-3.jpg',
    source: 'Shein',
    category: 'mode',
    badge: 'Nouveau',
    deliveryDays: '8-14 jours',
    rating: 4.7,
    reviews: 456,
    description: 'Sac bandouliere en cuir synthetique de haute qualite. Design minimaliste et elegant, parfait pour toutes les occasions.',
    colors: [
      { name: 'Camel', hex: '#D97706' },
      { name: 'Noir', hex: '#1C0A00' },
      { name: 'Beige', hex: '#FDE68A' },
    ],
  },
  {
    id: 'p4',
    name: 'Montre Connectee Sport',
    price: 55000,
    originalPrice: 72000,
    image: '/images/products/trending-4.jpg',
    source: 'Amazon',
    category: 'electronique',
    badge: 'Soldes',
    deliveryDays: '7-10 jours',
    rating: 4.9,
    reviews: 892,
    description: 'Montre connectee avec suivi d\'activite, frequence cardiaque et GPS. Ecran AMOLED et autonomie de 14 jours.',
    colors: [
      { name: 'Or', hex: '#D97706' },
      { name: 'Noir', hex: '#1C0A00' },
    ],
  },
  {
    id: 'p5',
    name: 'Sneakers Urbaines Minimalistes',
    price: 28000,
    image: '/images/products/trending-5.jpg',
    source: 'Shein',
    category: 'mode',
    badge: 'Nouveau',
    deliveryDays: '10-16 jours',
    rating: 4.5,
    reviews: 678,
    description: 'Sneakers blanches au design minimaliste. Confortables et polyvalentes, ideales pour un look decontracte.',
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    colors: [
      { name: 'Blanc', hex: '#FFFFFF' },
      { name: 'Beige', hex: '#FDE68A' },
    ],
  },
  {
    id: 'p6',
    name: 'Robe Imprimee Florale Ete',
    price: 22000,
    originalPrice: 35000,
    image: '/images/products/trending-6.jpg',
    source: 'Shein',
    category: 'mode',
    badge: 'Soldes',
    deliveryDays: '12-18 jours',
    rating: 4.4,
    reviews: 345,
    description: 'Robe d\'ete en soie imprimee florale. Coupe elegante et fluide, parfaite pour les journees chaudes.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Floral', hex: '#FCD34D' },
      { name: 'Rose', hex: '#EF4444' },
    ],
  },
]

export const catalogueProducts: Product[] = [
  ...trendingProducts,
  {
    id: 'p7',
    name: 'Sac a Dos Laptop Premium',
    price: 35000,
    image: '/images/products/catalogue-1.jpg',
    source: 'Amazon',
    category: 'accessoires',
    deliveryDays: '7-12 jours',
    rating: 4.6,
    reviews: 523,
    description: 'Sac a dos pour ordinateur portable avec compartiment rembourre, port USB integre et design ergonomique.',
    colors: [
      { name: 'Gris', hex: '#6B4C2A' },
      { name: 'Noir', hex: '#1C0A00' },
    ],
  },
  {
    id: 'p8',
    name: 'Casque Audio Sans Fil Pro',
    price: 42000,
    originalPrice: 58000,
    image: '/images/products/catalogue-2.jpg',
    source: 'Amazon',
    category: 'electronique',
    badge: 'Soldes',
    deliveryDays: '7-10 jours',
    rating: 4.8,
    reviews: 912,
    description: 'Casque audio premium avec reduction de bruit active, son Hi-Res et autonomie de 30 heures.',
    colors: [
      { name: 'Noir', hex: '#1C0A00' },
    ],
  },
  {
    id: 'p9',
    name: 'Kit Soin Visage Premium',
    price: 27500,
    image: '/images/products/catalogue-3.jpg',
    source: 'Shein',
    category: 'beaute',
    badge: 'Nouveau',
    deliveryDays: '12-18 jours',
    rating: 4.3,
    reviews: 267,
    description: 'Kit complet de soins du visage avec nettoyant, serum et creme hydratante. Ingredients naturels.',
    colors: [
      { name: 'Standard', hex: '#FFFDF5' },
    ],
  },
  {
    id: 'p10',
    name: 'Lampe de Bureau Design',
    price: 19000,
    image: '/images/products/catalogue-4.jpg',
    source: 'AliExpress',
    category: 'maison',
    deliveryDays: '10-15 jours',
    rating: 4.5,
    reviews: 189,
    description: 'Lampe de bureau moderne avec eclairage LED reglable, design minimaliste et bras articule.',
    colors: [
      { name: 'Blanc', hex: '#FFFFFF' },
      { name: 'Noir', hex: '#1C0A00' },
    ],
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('fr-CM', {
    style: 'decimal',
    minimumFractionDigits: 0,
  }).format(price) + ' FCFA'
}
